"""initial_schema

Revision ID: 128077f8d4fe
Revises: 
Create Date: 2026-02-24 13:21:14.542301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '128077f8d4fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_lookup', 'otp_codes', ['identifier', 'purpose', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('predictors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sebi_reg_no', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['predictors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_predictors_parent', 'predictors', ['parent_id'], unique=False, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.create_index('idx_predictors_type', 'predictors', ['type'], unique=False)
    op.create_table('stock_daily_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_stock_daily_prices_stock_date')
    )
    op.create_index('idx_stock_daily_prices_lookup', 'stock_daily_prices', ['stock_id', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('bse_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('auth_methods', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=200), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ban_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name='user_has_identity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user', 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_read IS false'))
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predictor_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_at_prediction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('default_eval_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_archive_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_quote', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('extraction_method', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending_review', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictors.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_approved_pending', 'predictions', ['default_eval_date'], unique=False, postgresql_where=sa.text("status = 'approved'"))
    op.create_index('idx_predictions_date', 'predictions', [sa.literal_column('prediction_date DESC')], unique=False)
    op.create_index('idx_predictions_predictor', 'predictions', ['predictor_id', sa.literal_column('prediction_date DESC')], unique=False)
    op.create_index('idx_predictions_status', 'predictions', ['status'], unique=False)
    op.create_index('idx_predictions_stock', 'predictions', ['stock_id', sa.literal_column('prediction_date DESC')], unique=False)
    op.create_table('predictor_scorecards',
    sa.Column('predictor_id', sa.UUID(), nullable=False),
    sa.Column('total_predictions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('misses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('partial_hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending', sa.Integer(), server_default='0', nullable=False),
    sa.Column('accuracy_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_deviation_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_upside_predicted', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('best_sector', sa.String(length=100), nullable=True),
    sa.Column('worst_sector', sa.String(length=100), nullable=True),
    sa.Column('sector_accuracy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('streak_current', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_prediction_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictors.id'], ),
    sa.PrimaryKeyConstraint('predictor_id')
    )
    op.create_index('idx_scorecards_accuracy', 'predictor_scorecards', [sa.literal_column('accuracy_pct DESC')], unique=False, postgresql_where=sa.text('total_predictions >= 10'))
    op.create_table('user_followed_predictors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('predictor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['predictor_id'], ['predictors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'predictor_id')
    )
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stock_id')
    )
    op.create_table('prediction_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('outcome_status', sa.String(length=20), nullable=False),
    sa.Column('actual_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deviation_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index('idx_outcomes_status', 'prediction_outcomes', ['outcome_status'], unique=False)
    op.create_table('prediction_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('promoted_to', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promoted_to'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suggestions_status', 'prediction_suggestions', ['status', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_suggestions_status', table_name='prediction_suggestions')
    op.drop_table('prediction_suggestions')
    op.drop_index('idx_outcomes_status', table_name='prediction_outcomes')
    op.drop_table('prediction_outcomes')
    op.drop_table('user_watchlist')
    op.drop_table('user_followed_predictors')
    op.drop_index('idx_scorecards_accuracy', table_name='predictor_scorecards', postgresql_where=sa.text('total_predictions >= 10'))
    op.drop_table('predictor_scorecards')
    op.drop_index('idx_predictions_stock', table_name='predictions')
    op.drop_index('idx_predictions_status', table_name='predictions')
    op.drop_index('idx_predictions_predictor', table_name='predictions')
    op.drop_index('idx_predictions_date', table_name='predictions')
    op.drop_index('idx_predictions_approved_pending', table_name='predictions', postgresql_where=sa.text("status = 'approved'"))
    op.drop_table('predictions')
    op.drop_index('idx_notifications_user', table_name='notifications', postgresql_where=sa.text('is_read IS false'))
    op.drop_table('notifications')
    op.drop_table('users')
    op.drop_table('stocks')
    op.drop_index('idx_stock_daily_prices_lookup', table_name='stock_daily_prices')
    op.drop_table('stock_daily_prices')
    op.drop_index('idx_predictors_type', table_name='predictors')
    op.drop_index('idx_predictors_parent', table_name='predictors', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_table('predictors')
    op.drop_index('idx_otp_lookup', table_name='otp_codes', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
