"""add_login_events_table

Revision ID: 31ce9a97f0d5
Revises: fc5d95390eef
Create Date: 2026-02-26 15:19:12.767716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ce9a97f0d5'
down_revision: Union[str, None] = 'fc5d95390eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_method', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_events_user_id', 'login_events', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed announcement runtime config keys
    runtime_config = sa.table(
        "runtime_config",
        sa.column("key", sa.String),
        sa.column("value", sa.String),
        sa.column("description", sa.String),
    )
    op.bulk_insert(runtime_config, [
        {
            "key": "announcement_text",
            "value": "",
            "description": "Public announcement banner text (empty = hidden)",
        },
        {
            "key": "announcement_type",
            "value": "info",
            "description": "Announcement banner style: info | warning | critical",
        },
    ])


def downgrade() -> None:
    # Remove seeded config keys
    op.execute("DELETE FROM runtime_config WHERE key IN ('announcement_text', 'announcement_type')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_events_user_id', table_name='login_events')
    op.drop_table('login_events')
    # ### end Alembic commands ###
