"""widen_otp_code_for_sha256

Revision ID: 5c3a9111b753
Revises: 36d7ec699ed1
Create Date: 2026-02-25 00:19:22.020292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3a9111b753'
down_revision: Union[str, None] = '36d7ec699ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_codes', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otp_codes', 'code',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
