"""add_runtime_config_table

Revision ID: fc5d95390eef
Revises: 842ae0e85e90
Create Date: 2026-02-26 14:00:25.200391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5d95390eef'
down_revision: Union[str, None] = '842ae0e85e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # Seed initial config keys
    runtime_config = sa.table(
        'runtime_config',
        sa.column('key', sa.String),
        sa.column('value', sa.Text),
        sa.column('description', sa.String),
    )
    op.bulk_insert(runtime_config, [
        {'key': 'maintenance_mode', 'value': 'false', 'description': 'Enable maintenance mode banner'},
        {'key': 'max_predictions_per_day', 'value': '100', 'description': 'Daily prediction submission cap'},
        {'key': 'evaluation_enabled', 'value': 'true', 'description': 'Enable automatic evaluation pipeline'},
        {'key': 'registration_enabled', 'value': 'true', 'description': 'Allow new user registration'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_config')
    # ### end Alembic commands ###
